### ISSUE TITLE
problem during make 

### ISSUE THREAD

**Issue by zhangxiutao** [baloneymath/anaroute#1]
[100%] Linking CXX executable ../bin/anaroute
/usr/bin/ld: CMakeFiles/anaroute.dir/src/parser/parLef.cpp.o: in function `ANAROUTE::LefReader::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
parLef.cpp:(.text+0x4d5): undefined reference to `LefParser::read(LefParser::LefDataBase&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/parser/parGds.cpp.o: in function `ANAROUTE::GdsReader::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
parGds.cpp:(.text+0x1b6e): undefined reference to `GdsParser::GdsDB::GdsReader::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: parGds.cpp:(.text+0x1bdc): undefined reference to `GdsParser::GdsDB::GdsDB::extractCell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/writer/wrLayout.cpp.o: in function `ANAROUTE::LayoutWriter::readPlacementGds(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GdsParser::GdsDB::GdsDB&)':
wrLayout.cpp:(.text+0xb9): undefined reference to `GdsParser::GdsDB::GdsReader::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/writer/wrLayout.cpp.o: in function `ANAROUTE::LayoutWriter::addTxt2Cell(GdsParser::GdsDB::GdsCell&, int, ANAROUTE::Point<int> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, double)':
wrLayout.cpp:(.text+0x224): undefined reference to `GdsParser::GdsDB::GdsCell::addText(int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::polygon::point_data<int> const&, int, int, double, double, int)'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/writer/wrLayout.cpp.o: in function `ANAROUTE::LayoutWriter::writeGds(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
wrLayout.cpp:(.text+0xbef): undefined reference to `GdsParser::GdsDB::GdsDB::getCell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: wrLayout.cpp:(.text+0xc1b): undefined reference to `GdsParser::GdsDB::GdsDB::extractCell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: wrLayout.cpp:(.text+0xd72): undefined reference to `GdsParser::GdsDB::GdsWriter::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/writer/wrDumb.cpp.o: in function `ANAROUTE::DumbWriter::readPlacementGds(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GdsParser::GdsDB::GdsDB&)':
wrDumb.cpp:(.text+0x179): undefined reference to `GdsParser::GdsDB::GdsReader::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/writer/wrDumb.cpp.o: in function `ANAROUTE::DumbWriter::write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
wrDumb.cpp:(.text+0x79b): undefined reference to `GdsParser::GdsDB::GdsDB::extractCell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o): in function `GdsParser::read(GdsParser::GdsDataBaseKernel&, std::string const&)':
GdsReader.cpp:(.text+0x15e0): undefined reference to `gzstreambase::gzstreambase(char const*, int)'
/usr/bin/ld: GdsReader.cpp:(.text+0x1686): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o): in function `igzstream::~igzstream()':
GdsReader.cpp:(.text._ZN9igzstreamD1Ev[_ZN9igzstreamD1Ev]+0x46): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o): in function `virtual thunk to igzstream::~igzstream()':
GdsReader.cpp:(.text._ZN9igzstreamD1Ev[_ZN9igzstreamD1Ev]+0xc0): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o): in function `non-virtual thunk to igzstream::~igzstream()':
GdsReader.cpp:(.text._ZN9igzstreamD1Ev[_ZN9igzstreamD1Ev]+0x13d): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o): in function `virtual thunk to igzstream::~igzstream()':
GdsReader.cpp:(.text._ZN9igzstreamD0Ev[_ZN9igzstreamD0Ev]+0x4d): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o):GdsReader.cpp:(.text._ZN9igzstreamD0Ev[_ZN9igzstreamD0Ev]+0xcf): more undefined references to `gzstreambase::~gzstreambase()' follow
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o):(.data.rel.ro._ZTI9igzstream[_ZTI9igzstream]+0x18): undefined reference to `typeinfo for gzstreambase'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o):(.data.rel.ro._ZTC9igzstream0_12gzstreambase[_ZTV9igzstream]+0x10): undefined reference to `typeinfo for gzstreambase'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o):(.data.rel.ro._ZTC9igzstream0_12gzstreambase[_ZTV9igzstream]+0x38): undefined reference to `typeinfo for gzstreambase'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `ogzstream::~ogzstream()':
GdsWriter.cpp:(.text._ZN9ogzstreamD1Ev[_ZN9ogzstreamD1Ev]+0x42): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `non-virtual thunk to ogzstream::~ogzstream()':
GdsWriter.cpp:(.text._ZN9ogzstreamD1Ev[_ZN9ogzstreamD1Ev]+0xb9): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `virtual thunk to ogzstream::~ogzstream()':
GdsWriter.cpp:(.text._ZN9ogzstreamD1Ev[_ZN9ogzstreamD1Ev]+0x12c): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `virtual thunk to ogzstream::~ogzstream()':
GdsWriter.cpp:(.text._ZN9ogzstreamD0Ev[_ZN9ogzstreamD0Ev]+0x49): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `non-virtual thunk to ogzstream::~ogzstream()':
GdsWriter.cpp:(.text._ZN9ogzstreamD0Ev[_ZN9ogzstreamD0Ev]+0xd1): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o):GdsWriter.cpp:(.text._ZN9ogzstreamD0Ev[_ZN9ogzstreamD0Ev]+0x142): more undefined references to `gzstreambase::~gzstreambase()' follow
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `GdsParser::GdsStream::GdsStream(char const*)':
GdsWriter.cpp:(.text._ZN9GdsParser9GdsStreamC2EPKc[_ZN9GdsParser9GdsStreamC5EPKc]+0x24c): undefined reference to `gzstreambase::gzstreambase(char const*, int)'
/usr/bin/ld: GdsWriter.cpp:(.text._ZN9GdsParser9GdsStreamC2EPKc[_ZN9GdsParser9GdsStreamC5EPKc]+0x41d): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o):(.data.rel.ro._ZTI9ogzstream[_ZTI9ogzstream]+0x18): undefined reference to `typeinfo for gzstreambase'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o):(.data.rel.ro._ZTC9ogzstream0_12gzstreambase[_ZTV9ogzstream]+0x10): undefined reference to `typeinfo for gzstreambase'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o):(.data.rel.ro._ZTC9ogzstream0_12gzstreambase[_ZTV9ogzstream]+0x38): undefined reference to `typeinfo for gzstreambase'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/anaroute.dir/build.make:792: ../bin/anaroute] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/anaroute.dir/all] Error 2

How to solve this problem?

**Comment by krzhu** [comment]
Try removing this line: https://github.com/baloneymath/anaroute/blob/0aee0dcd0068fac73546a24141ae51313bbe553a/CMakeLists.txt#L61
 and the other zlib things in the file. 

The zlib issue might be related to limbo. I am using a pretty old version of limbo. I will try take a look soon.

**Comment by zhangxiutao** [comment]
after remove all the Zlib related lines, the problem seems still exists
[ 90%] Linking CXX executable ../bin/anaroute
/usr/bin/ld: CMakeFiles/anaroute.dir/src/parser/parLef.cpp.o: in function `ANAROUTE::LefReader::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
parLef.cpp:(.text+0x4d5): undefined reference to `LefParser::read(LefParser::LefDataBase&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/parser/parGds.cpp.o: in function `ANAROUTE::GdsReader::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
parGds.cpp:(.text+0x1b6e): undefined reference to `GdsParser::GdsDB::GdsReader::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: parGds.cpp:(.text+0x1bdc): undefined reference to `GdsParser::GdsDB::GdsDB::extractCell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/writer/wrLayout.cpp.o: in function `ANAROUTE::LayoutWriter::readPlacementGds(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GdsParser::GdsDB::GdsDB&)':
wrLayout.cpp:(.text+0xb9): undefined reference to `GdsParser::GdsDB::GdsReader::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/writer/wrLayout.cpp.o: in function `ANAROUTE::LayoutWriter::addTxt2Cell(GdsParser::GdsDB::GdsCell&, int, ANAROUTE::Point<int> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, double)':
wrLayout.cpp:(.text+0x224): undefined reference to `GdsParser::GdsDB::GdsCell::addText(int, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::polygon::point_data<int> const&, int, int, double, double, int)'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/writer/wrLayout.cpp.o: in function `ANAROUTE::LayoutWriter::writeGds(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
wrLayout.cpp:(.text+0xbef): undefined reference to `GdsParser::GdsDB::GdsDB::getCell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: wrLayout.cpp:(.text+0xc1b): undefined reference to `GdsParser::GdsDB::GdsDB::extractCell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: wrLayout.cpp:(.text+0xd72): undefined reference to `GdsParser::GdsDB::GdsWriter::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/writer/wrDumb.cpp.o: in function `ANAROUTE::DumbWriter::readPlacementGds(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, GdsParser::GdsDB::GdsDB&)':
wrDumb.cpp:(.text+0x179): undefined reference to `GdsParser::GdsDB::GdsReader::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/anaroute.dir/src/writer/wrDumb.cpp.o: in function `ANAROUTE::DumbWriter::write(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
wrDumb.cpp:(.text+0x79b): undefined reference to `GdsParser::GdsDB::GdsDB::extractCell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o): in function `GdsParser::read(GdsParser::GdsDataBaseKernel&, std::string const&)':
GdsReader.cpp:(.text+0x15e0): undefined reference to `gzstreambase::gzstreambase(char const*, int)'
/usr/bin/ld: GdsReader.cpp:(.text+0x1686): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o): in function `igzstream::~igzstream()':
GdsReader.cpp:(.text._ZN9igzstreamD1Ev[_ZN9igzstreamD1Ev]+0x46): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o): in function `virtual thunk to igzstream::~igzstream()':
GdsReader.cpp:(.text._ZN9igzstreamD1Ev[_ZN9igzstreamD1Ev]+0xc0): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o): in function `non-virtual thunk to igzstream::~igzstream()':
GdsReader.cpp:(.text._ZN9igzstreamD1Ev[_ZN9igzstreamD1Ev]+0x13d): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o): in function `virtual thunk to igzstream::~igzstream()':
GdsReader.cpp:(.text._ZN9igzstreamD0Ev[_ZN9igzstreamD0Ev]+0x4d): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o):GdsReader.cpp:(.text._ZN9igzstreamD0Ev[_ZN9igzstreamD0Ev]+0xcf): more undefined references to `gzstreambase::~gzstreambase()' follow
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o):(.data.rel.ro._ZTI9igzstream[_ZTI9igzstream]+0x18): undefined reference to `typeinfo for gzstreambase'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o):(.data.rel.ro._ZTC9igzstream0_12gzstreambase[_ZTV9igzstream]+0x10): undefined reference to `typeinfo for gzstreambase'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsReader.cpp.o):(.data.rel.ro._ZTC9igzstream0_12gzstreambase[_ZTV9igzstream]+0x38): undefined reference to `typeinfo for gzstreambase'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `ogzstream::~ogzstream()':
GdsWriter.cpp:(.text._ZN9ogzstreamD1Ev[_ZN9ogzstreamD1Ev]+0x42): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `non-virtual thunk to ogzstream::~ogzstream()':
GdsWriter.cpp:(.text._ZN9ogzstreamD1Ev[_ZN9ogzstreamD1Ev]+0xb9): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `virtual thunk to ogzstream::~ogzstream()':
GdsWriter.cpp:(.text._ZN9ogzstreamD1Ev[_ZN9ogzstreamD1Ev]+0x12c): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `virtual thunk to ogzstream::~ogzstream()':
GdsWriter.cpp:(.text._ZN9ogzstreamD0Ev[_ZN9ogzstreamD0Ev]+0x49): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `non-virtual thunk to ogzstream::~ogzstream()':
GdsWriter.cpp:(.text._ZN9ogzstreamD0Ev[_ZN9ogzstreamD0Ev]+0xd1): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o):GdsWriter.cpp:(.text._ZN9ogzstreamD0Ev[_ZN9ogzstreamD0Ev]+0x142): more undefined references to `gzstreambase::~gzstreambase()' follow
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o): in function `GdsParser::GdsStream::GdsStream(char const*)':
GdsWriter.cpp:(.text._ZN9GdsParser9GdsStreamC2EPKc[_ZN9GdsParser9GdsStreamC5EPKc]+0x24c): undefined reference to `gzstreambase::gzstreambase(char const*, int)'
/usr/bin/ld: GdsWriter.cpp:(.text._ZN9GdsParser9GdsStreamC2EPKc[_ZN9GdsParser9GdsStreamC5EPKc]+0x41d): undefined reference to `gzstreambase::~gzstreambase()'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o):(.data.rel.ro._ZTI9ogzstream[_ZTI9ogzstream]+0x18): undefined reference to `typeinfo for gzstreambase'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o):(.data.rel.ro._ZTC9ogzstream0_12gzstreambase[_ZTV9ogzstream]+0x10): undefined reference to `typeinfo for gzstreambase'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/libgdsparser.a(GdsWriter.cpp.o):(.data.rel.ro._ZTC9ogzstream0_12gzstreambase[_ZTV9ogzstream]+0x38): undefined reference to `typeinfo for gzstreambase'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/anaroute.dir/build.make:787: ../bin/anaroute] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/anaroute.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by baloneymath** [comment]
It seems like it's the same issue with this post: (https://bbs.archlinux.org/viewtopic.php?id=141750.)

Can you try adding the g++ flags `-lgzstream -lz`  to link those libraries and see if it works?

**Comment by krzhu** [comment]
I have updated the master branch. It should be fine now.
