### ISSUE TITLE
assertion failed when source examples/adc1/run.sh

### ISSUE THREAD

**Issue by zhangxiutao** [baloneymath/anaroute#2]
Hi, when I try to run examples/adc1/run.sh, an assertion failed. How to solve this problem? Thanks.
AcsMgr::computeAcs Start Access Points Generation

DrMgr::solve Start Detailed Routing
DrSymmetry::solve Start max symmetric detection
DrSymmetry::solve Self-sym: gnd
DrSymmetry::solve Self-sym: ncas
DrSymmetry::solve Self-sym: vcm
DrSymmetry::solve Self-sym: vdd
DrSymmetry::solve Sym:      vim vip
DrSymmetry::solve Sym:      vom vop
DrSymmetry::solve Self-sym: vs
DrSymmetry::solve Self-sym: vcmon
DrSymmetry::solve Self-sym: pcas
DrSymmetry::solve Self-sym: bias2
DrSymmetry::solve Self-sym: tail1
DrSymmetry::solve Self-sym: nbias_tail
DrSymmetry::solve Self-sym: vcmop
DrSymmetry::solve Self-sym: net0108
DrSymmetry::solve Self-sym: vs2
DrSymmetry::solve Sym:      vo1p vo1m
DrSymmetry::solve Sym:      casn casp
DrSymmetry::solve Self-sym: bias1
DrSymmetry::solve Self-sym: net096
DrSymmetry::solve Sym:      cas2n cas2p
DrSymmetry::solve Self-sym: net088
python: /tmp/pip-kjKTFP-build/src/dr/drRoutable.cpp:466: ANAROUTE::Int_t ANAROUTE::DrRoutable::totallySymPinIdx(const ANAROUTE::Pin&, ANAROUTE::Vector_t<std::vector<ANAROUTE::Box<int>, std::allocator<ANAROUTE::Box<int> > > >&): Assertion `vPinIndices.size() == 1' failed.
Aborted (core dumped)

**Comment by krzhu** [comment]
Try cicc2021 branch, it is synchronized with the current publications. We might need some time to look into this issue.
